name: CI
on:
  workflow_dispatch:
jobs:
  Test:
    name: Run tests
    runs-on: ${{ inputs.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.branch }}
      - name: Install JDK
        uses: actions/setup-java@v5
        with:
          java-version: ${{ inputs.jdk }}
          distribution: temurin
      - name: Run tests
        if: always()
        run: mvn -s .github/maven-ci-settings.xml -q clean verify -B ${{ inputs.profile }}
      - name: Run tests
        if: always()
        run: |
          # io_uring testing requires more locked memory for kernel ring buffers than the default 8MB limit
          sudo prlimit --pid $$ --memlock=16777216:16777216
          mvn -s .github/maven-ci-settings.xml -q clean verify -B ${{ inputs.profile }}
    strategy:
      fail-fast: false
